<?php

namespace Database\Seeders;

use App\Models\Author;
use Illuminate\Database\Seeder;

class AuthorSeeder extends Seeder
{
    public function run(): void
    {
        $authors = [
        [
            'first_name' => 'Bryan',
            'last_name' => 'Williams',
            'title' => 'PTM Founder & Assistant Manuscript Project Lead',
            'middle_initial' => 'S',
            'bio' => '<p>Bryan Scott Williams is the creator and founder of Project Truth Ministries. Bryan has a deep love for all things related to the Bible. He has a history degree from the University of North Carolina at Pembroke, he has been a Bible teacher since 2019, and he has been studying Biblical text criticism since 2011. Bryan is an editor, team lead, researcher and transcriber for Biblical New Testament Hebrew Manuscript Projects and has been working on Hebrew Manuscript projects since 2021. He is a collector of many copies of Hebrew New Testament manuscripts and is a documenter of Biblical archaeology. He also has assisted on two expeditions of discovery and documentation of the real Mount Sinai in Saudi Arabia. Bryan also periodically gives tours through Living Passages Tours to Mount Sinai. He is completely consumed with getting the truth out to the world. His goal is to share the truth about the Bible to as many people as he can.</p>',
            'image' => 'bwilliams.jpg',
            'active' => 1,
            'team_member' => 1,
            'priority' => 1,
            'social_links' => null,
            'facebook' => null,
            'youtube' => 'https://www.youtube.com/@ProjectTruthMinistries',
            'rumble' => 'https://www.rumble.com/ProjectTruthMinistries',
            'linkedin' => null,
            'truthsocial' => null,
            'tiktok' => null,
            'x' => null,
            'created_at' => '2026-08-10 21:50:43',
            'updated_at' => '2026-08-12 19:24:54',
            'deleted_at' => null,
        ],
        [
            'first_name' => 'Janice',
            'last_name' => 'Baca',
            'title' => 'Translator, Hebrew Grammarian & Project Lead',
            'middle_initial' => 'F',
            'bio' => '<p>Janice F. Baca is a biblical Hebrew translator, independent researcher, author, and teacher whose work explores Scripture through its Hebrew and broader Semitic foundations. She has completed graduate-level coursework in Theology, Biblical Hebrew, and Biblical Aramaic, equipping her with a strong foundation for advanced study in the languages, texts, and cultures of the ancient Near East.</p><p>Her research includes translating the Cochin Cambridge Hebrew New Testament and analyzing other New Testament manuscripts for possible late Second Temple Hebrew markers. This work is shared as a free download through the Project Truth Ministries website, making her research accessible to students, teachers, and readers seeking a deeper understanding of the Hebrew background of the New Testament.</p><p>Janice is the author of several published books, including Discover the 144,000: and Their Song; Demons, Devils, Deities: And the Four Witnesses; Power-of-God-Singing: in the Hebrew New Testament; and her newest publication, Cleansing the Soul, the House, and the Land for the Final March. Her translation work also includes book-format editions of the Cochin Revelation, The Scroll of Mysteries: Cochin Hebrew Revelation, and the Cochin Hebrew James, The Return Letter of James: The Cochin Hebrew James, both published on Amazon and available as free downloads through ProjectTruthMinistries.org. She is also the author of the published paper "The Cochin Hebrew New Testament Manuscripts at Cambridge (MS Oo.1.32, Oo.1.16.1, Oo.1.16.2): Late Copies with Signs of an Early Semitic Tradition," published in the European Hebrew Journal, Vol. 1, No. 1 (2026), where she also serves as the USA Ambassador.</p><p>Janice is now directing her studies toward graduate-level ancient Semitic languages, including Ugaritic and Akkadian, in order to further the mission of Project Truth Ministries by deepening biblical research, preserving ancient linguistic heritage, and sharing these insights with others.</p>',
            'image' => 'jbaca.jpg',
            'active' => 1,
            'team_member' => 1,
            'priority' => 2,
            'social_links' => null,
            'facebook' => 'https://www.facebook.com/JaniceFBaca',
            'youtube' => 'https://www.youtube.com/@JaniceFBaca_Translator',
            'rumble' => null,
            'linkedin' => null,
            'truthsocial' => null,
            'tiktok' => 'https://www.tiktok.com/@janicefbaca_translator',
            'x' => null,
            'created_at' => '2026-08-10 21:50:43',
            'updated_at' => '2026-08-12 18:47:37',
            'deleted_at' => null,
        ],
        [
            'first_name' => 'Jonathan',
            'last_name' => 'Meyer',
            'title' => 'Transcriber',
            'middle_initial' => null,
            'bio' => '<p>Jonathan Meyer is a highly dedicated and self-motivated individual, learning Biblical Hebrew in his personal studies. Jonathan\'s concern regarding deceptions in Biblical translations led him to dedicate his time in research and transcribe Hebrew New Testament manuscripts for over five years! Additionally, Jonathan continues to expand his Hebrew grammar understanding through team trainings and through the Cochin Hebrew Revelation text criticism video series completed by Hebrew Grammarian, Janice F. Baca and history scholar, Bryan S. Williams. And, as a transcriber, Jonathan saves the translation team countless hours by analyzing and transcribing the Hebrew that allows more flexibility for the translation team to publish their findings. It is with great passion that Jonathan encourages people to dedicate and study the Cochin Hebrew New Testament MS Oo.1.32, Oo.1.16 texts to discover the unique language connected to the First Century language!</p>',
            'image' => 'jmeyer.png',
            'active' => 1,
            'team_member' => 1,
            'priority' => 3,
            'social_links' => null,
            'facebook' => null,
            'youtube' => null,
            'rumble' => null,
            'linkedin' => null,
            'truthsocial' => null,
            'tiktok' => null,
            'x' => null,
            'created_at' => '2026-08-10 21:50:43',
            'updated_at' => '2026-08-11 22:12:20',
            'deleted_at' => null,
        ],
        [
            'first_name' => 'Victor',
            'last_name' => 'Nuñez',
            'title' => 'Researcher & Transcriber',
            'middle_initial' => null,
            'bio' => '<p>Victor Nuñez was previously an average Sunday church attender until God called him to Torah through his wife, Erica. In 2018, he was introduced to eating Biblically clean foods, the seventh day Sabbath, and Yehovah\'s commanded Feast days. This new revelation of God\'s word led Victor on a journey to discover and recover the original writings of the Hebrew New Testament.</p><p>Then in August of 2023, Victor pursued the Hebrew New Testament studies. Therefore, after three years of hearing reports that the Hebrew New Testament was to be published by one scholar, Victor discovered the translations available in the scholar\'s Hebrew to English translation publication of that Hebrew New Testament manuscript was not true to the English text in comparison to which God spoke. It was at that time, God showed Victor the necessity to learn Biblical Hebrew. Thus, Victor took the initiative to learn Biblical Hebrew in his personal home studies and later began formal studies in Biblical Hebrew through the Israel Institute of Biblical Studies based in Jerusalem, Israel. And in the middle of 2024, The Scroll of Mysteries: Cochin Hebrew Revelation MS Oo.1.16.2 was published and in turn, caught Victor\'s complete attention. He was able to connect with Mrs. Janice F. Baca and question the Cochin manuscripts validity. Therefore, after several months of reviewing Janice Baca and Bryan Williams\' release of their Revelation video series with their text criticism, Victor learned that Matthew was in the process of review and publication and saw an opportunity to help transcribe and join the Project Truth Ministries team. High-quality work is a significant asset to the organization and the Kingdom of God.</p>',
            'image' => 'vnunez.jpg',
            'active' => 1,
            'team_member' => 1,
            'priority' => 4,
            'social_links' => null,
            'facebook' => null,
            'youtube' => null,
            'rumble' => null,
            'linkedin' => null,
            'truthsocial' => null,
            'tiktok' => null,
            'x' => null,
            'created_at' => '2026-08-10 21:50:43',
            'updated_at' => '2026-08-11 22:12:07',
            'deleted_at' => null,
        ],
        [
            'first_name' => 'Justin',
            'last_name' => 'Leoni',
            'title' => 'Software Engineer & Researcher',
            'middle_initial' => 'S',
            'bio' => '<p style="text-align:justify;">Justin Leoni is a senior software engineer and independent biblical researcher whose professional career spans more than two decades designing custom software architectures, enterprise systems, and technical infrastructures. After living most of his life as an agnostic, he began an intentional spiritual search in 2021. By 2023 he had married Wendy Leoni and committed himself fully to the pursuit of Yehovah, turning decades of engineering discipline toward the recovery of first-century Hebraic sources and covenantal fidelity.</p><p style="text-align:justify;"><br>His early research was marked by exhaustive manual study—working through concordances, multiple Bible versions, antique Bibles that preserve additional texts, and historical Christian documents—while simultaneously building a comprehensive Bible application to organize the material. It soon became clear that the Greek manuscript tradition could not represent the original Semitic source stream. In late 2023, together with Wendy, he launched a Christian podcast to share these emerging insights, and he completed prophetic training at Christian International. Still sensing that existing tools were insufficient, by late 2024 he engineered the first biblical-first AI wrapper—the Master Hebraic Restoration Framework—designed to impose corrective Hebraic lenses on artificial intelligence systems and prevent Hellenistic default readings.</p><p style="text-align:justify;"><br>Encountering the Cochin Hebrew Scroll of Mysteries (Revelation) confirmed for him that an authentic Hebrew Vorlage had been preserved. He invited Project Truth Ministries onto the podcast and, by late 2025, joined the PTM team. Since that time he has developed a fully self-contained local AI research system operating entirely within his own network, along with numerous specialized software packages for manuscript transcription, labor automation, API integration, and accelerated textual analysis. These tools now support the ongoing recovery and dissemination of the Cochin witnesses and related Hebraic materials.</p><p style="text-align:justify;"><br>Justin has dedicated his remaining time and technical skill to the restoration of Yehovah\'s and Yeshua\'s words as they were originally given—prioritizing Cochin Hebrew primacy, active emunah, and the narrow path of covenantal allegiance over later philosophical overlays.</p>',
            'image' => 'jleoni.jpg',
            'active' => 1,
            'team_member' => 1,
            'priority' => 5,
            'social_links' => null,
            'facebook' => null,
            'youtube' => null,
            'rumble' => 'https://rumble.com/c/UnderTheOakTree',
            'linkedin' => null,
            'truthsocial' => 'https://truthsocial.com/@italianmob',
            'tiktok' => null,
            'x' => 'https://x.com/jleoni',
            'created_at' => '2026-08-10 21:50:43',
            'updated_at' => '2026-08-15 15:43:37',
            'deleted_at' => null,
        ],
        [
            'first_name' => 'Wendy',
            'last_name' => 'Leoni',
            'title' => 'Researcher',
            'middle_initial' => 'C',
            'bio' => '<p>Wendy brings a unique analytical lens to scriptural research, backed by 18 years of professional experience in data analysis. Throughout her career, she mastered a core business principle: inaccurate data always produces inaccurate results. Ultimately, Yehovah redirected this exact passion for finding truth within complex data sets toward investigating ancient biblical texts.</p><p>Her deeply personal walk with Yeshua took a pivotal turn between 2017 and 2022. During a season of profound family loss that perfectly matched a prophetic dream given to her years prior, she began to heavily rely on the Holy Spirit\'s direct counsel. Out of the literal and spiritual storms of that season—symbolized by a sick, rotted oak tree that fell on her property, only for a vibrant new oak tree to grow in its place—Yehovah brought life after death. This refining fire opened her eyes to the stark contrast between traditional religious dogmas and the living Word of God. Recognizing how modern paradigms often obscure original truths, she committed her analytical skills to studying first-century contexts and Hebrew roots.</p><p>Following this season of restoration, Wendy married her husband, Justin, and Yehovah beautifully gave her a new name: Leoni. Meaning "Lions" in Italian, the name carries a profound kingdom connection, mirroring a theme frequently championed by Bryan in his own podcasts. Moving from their initial podcast work, Wendy and Justin transitioned their full attention to the foundational work of translating and uncovering scriptural texts. Wendy\'s specific focus centers on meticulous comparative analysis between Greek and Hebrew terms. By tracing translations back to their cultural origins—such as uncovering how Greek concepts like pistis distorted the active, covenant-based reality of the Hebrew emunah (faith)—she helps believers untangle their walk from historical errors.</p><p>Yehovah\'s precise guidance systematically connected Wendy and Justin to Project Truth Ministries. While deep in their translation studies, they discovered a podcast featuring Janice Baca discussing her Mount Sinai experience. The profound resonance of that testimony, combined with the clarity of Janice\'s translation of Revelation, served as a divine confirmation. Looking to share these rich, unfiltered Hebrew roots, Justin reached out to Bryan for an interview, quickly revealing a perfectly aligned kingdom mission. Today, Wendy is learning more and more about what Yehovah\'s Kingdom actually "looks" like and trying to help others see what He has revealed in their own walks.</p>',
            'image' => 'wleoni.jpg',
            'active' => 1,
            'team_member' => 1,
            'priority' => 6,
            'social_links' => null,
            'facebook' => null,
            'youtube' => null,
            'rumble' => 'https://rumble.com/c/UnderTheOakTree',
            'linkedin' => null,
            'truthsocial' => 'https://truthsocial.com/@chaseshope',
            'tiktok' => null,
            'x' => null,
            'created_at' => '2026-08-10 21:50:44',
            'updated_at' => '2026-08-12 18:50:16',
            'deleted_at' => null,
        ],
        [
            'first_name' => 'Stephen',
            'last_name' => 'Moran',
            'title' => 'Contributing Writer',
            'middle_initial' => null,
            'bio' => null,
            'image' => null,
            'active' => 0,
            'team_member' => 0,
            'priority' => 99,
            'social_links' => null,
            'facebook' => null,
            'youtube' => null,
            'rumble' => null,
            'linkedin' => null,
            'truthsocial' => null,
            'tiktok' => null,
            'x' => null,
            'created_at' => '2026-08-11 22:35:05',
            'updated_at' => '2026-08-12 18:36:34',
            'deleted_at' => null,
        ]
        ];

        foreach ($authors as $data) {
            Author::updateOrCreate(
                ['first_name' => $data['first_name'], 'last_name' => $data['last_name']],
                $data
            );
        }
    }
}
