<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
        [
            'title' => 'The Scroll of Mysteries:',
            'subtitle' => 'Cochin Hebrew Revelation',
            'slug' => 'scroll-of-mysteries-cochin-hebrew-revelation',
            'author_id' => 1,
            'body' => '<p>The Cochin Hebrew Revelation: Cochin Hebrew Revelation (Cambridge MS Oo.1.16.2) is a captivating Hebrew manuscript discovered in 1803 in the synagogue of the Black Jews in Cochin, India, by Claudius Buchanan. It features Hebrew grammatical markers based on the tradition of First-Century disciple writers.</p><p>What is Included in The Scroll of Mysteries Translation: The Scroll of Mysteries: Cochin Hebrew Revelation contains images, Hebrew transcription, English translation, interlinear tables, the corresponding Greek and Aramaic verses for comparison and commentary, revealing the mysteries discovered within the Hebrew grammar of the Cochin Hebrew Revelation.</p><p>Additionally, included is testimony of the miraculous events of the covenant we made at Mount Sinai, along with steps on how you can join in the covenant agreement with Yehovah. And in the back of the book is a copy of the Ketubah (written covenant) for those who wish to join us in this covenant promise.</p>',
            'isbn_13' => '979-8189959592',
            'isbn_10' => 'B0HC9PZDPR',
            'amazon_link' => 'https://www.amazon.com/Scroll-Mysteries-Cochin-Hebrew-Revelation/dp/B0HC9PZDPR/',
            'lulu_link' => null,
            'image_front' => 'the-scroll-of-mysteries.png',
            'image_back' => null,
            'image_inner' => null,
            'edition' => '3rd',
            'published_at' => '2024-11-15',
            'published' => 1,
            'active' => 1,
            'priority' => 0,
            'page_count' => 345,
            'language' => 'English',
            'price_usd' => '19.99',
            'created_at' => '2026-08-11 14:39:21',
            'updated_at' => '2026-08-11 23:21:28',
            'deleted_at' => null,
        ],
        [
            'title' => 'The Return Letter of James: The Cochin Hebrew James',
            'subtitle' => 'Translation and Commentary on the Cochin Hebrew James Manuscript',
            'slug' => 'return-letter-of-james-cochin-hebrew-james',
            'author_id' => 1,
            'body' => 'The Return Letter of James is a copy of the Hebrew letter written to the scattered twelve tribes of Israel by James (Yaakov) who was called “the brother of Yeshua” (see Mt 13:55; Mk 6:3). The Return Letter of James: Cochin James MS Oo.1.32 with some verses written in Mishnaic Hebrew with Aramaisms according to the First Century tradition. For it is believed that in the First Century of Judea, the talmidim (i.e. disciples) spoke rabbinic Hebrew – with a subset of rabbinic Hebrew represented in the Mishnah called "Mishnaic Hebrew." For in the First Century, after the destruction of the Temple in Jerusalem - and for the following couple of centuries, Mishnaic Hebrew was used and was also included in the Dead Sea Scrolls.The grammar of Cochin James contains some striking differences in the writing style of his letter that brings a deeper meaning to what is believed could be very close to the words by James (Yaakov) for the twelve tribes of Israel that are scattered abroad for this day.',
            'isbn_13' => '979-8344784014',
            'isbn_10' => 'B0DLB9M9TC',
            'amazon_link' => 'https://a.co/d/j8VQb3I',
            'lulu_link' => null,
            'image_front' => 'the-return-letter-of-james.png',
            'image_back' => null,
            'image_inner' => null,
            'edition' => '1st',
            'published_at' => '2023-09-22',
            'published' => 1,
            'active' => 1,
            'priority' => 5,
            'page_count' => 76,
            'language' => 'English',
            'price_usd' => '19.55',
            'created_at' => '2026-08-11 14:39:21',
            'updated_at' => '2026-08-11 20:58:43',
            'deleted_at' => null,
        ],
        [
            'title' => 'Demons, Devils, Deities:',
            'subtitle' => 'And the Four Witnesses',
            'slug' => 'demons-devils-deities-and-the-four-witnesses',
            'author_id' => 1,
            'body' => '<p>Tormenting dreams, sleep paralysis, and demonic influences are increasing and raging upon people. Whether it is noonday or midnight, the demonic and dark forces continue destroying unrelentingly, day in and day out, with what seems to be no relief in sight.</p><p>Yet, there is an answer, a prophecy. A prophecy given by Moses is coming to pass, and it is described in the Song of Moses. For Moses warned us of that day, and that day has arrived. And the only way to victory is simply one answer ̶ guaranteed.</p>',
            'isbn_13' => '979-8288364235',
            'isbn_10' => 'B0FDGW7SJQ',
            'amazon_link' => 'https://a.co/d/8cNd0Kp',
            'lulu_link' => null,
            'image_front' => 'demons-devils-deities.jpg',
            'image_back' => null,
            'image_inner' => null,
            'edition' => '1st',
            'published_at' => '2023-06-20',
            'published' => 1,
            'active' => 1,
            'priority' => 9,
            'page_count' => 158,
            'language' => 'English',
            'price_usd' => '15.99',
            'created_at' => '2026-08-11 14:39:21',
            'updated_at' => '2026-08-11 20:59:09',
            'deleted_at' => null,
        ],
        [
            'title' => 'Discover the 144,000:',
            'subtitle' => 'and Their Song',
            'slug' => 'discover-the-144000-and-their-song',
            'author_id' => 1,
            'body' => 'Janice F Baca unveils astonishing secrets hidden within The Scroll of Mysteries: Cochin Hebrew Revelation, linking them back to Ezekiel 9 and the ancient legendary Song of the Sea described in Exodus 15—a war song that was the first song and will become the last song at the end of the ages. She reimagines this renewed power-of-God song sung by the 144,000, restoring long-lost verses from the Qumran Caves that have been partially preserved for generations. These verses will be fully restored when Yeshua teaches them their song that no one else can learn. Most remarkably, she reveals, through Hebrew grammatical insights, who the 144,000 truly are: men, women, and children from both the past and the present! These chosen ones will be summoned to Jerusalem for their sealing for the Biblical feast day of the Day of Atonement, as Messiah Yeshua arrives from the Eastern gate, holding the seal in His hand, ready to claim them as His own!',
            'isbn_13' => '979-8902147251',
            'isbn_10' => 'B0G4XWQSWC',
            'amazon_link' => 'https://a.co/d/eWuN6vj',
            'lulu_link' => 'https://www.lulu.com/shop/janice-baca/discover-the-144000/paperback/product-nvj59ge.html?q=Janice+Baca&page=1&pageSize=4',
            'image_front' => 'discover-the-144000.png',
            'image_back' => null,
            'image_inner' => null,
            'edition' => '2nd',
            'published_at' => '2022-03-15',
            'published' => 1,
            'active' => 1,
            'priority' => 10,
            'page_count' => 136,
            'language' => 'English',
            'price_usd' => '19.99',
            'created_at' => '2026-08-11 14:39:21',
            'updated_at' => '2026-08-11 20:56:53',
            'deleted_at' => null,
        ],
        [
            'title' => 'Power-of-God-Singing:',
            'subtitle' => 'in the Hebrew New Testament',
            'slug' => 'power-of-god-singing-in-the-hebrew-new-testament',
            'author_id' => 1,
            'body' => 'Discover Janice Baca\'s powerful insights into the incredible power of God expressed through song, dance, and worship. Feel the divine energy that can bring healing, deliverance, and miracles — a force that will inspire and uplift you in these extraordinary times. In the darkest times, our call is to worship and praise our God like never before—because it is during these moments that the most extraordinary miracles happen! Join us in this powerful journey of faith and witness the impossible become possible.',
            'isbn_13' => '979-8901194263',
            'isbn_10' => 'B0G2G53WGM',
            'amazon_link' => 'https://a.co/d/9hpcQNR',
            'lulu_link' => 'https://lulu.com/shop/janice-baca/power-of-god-singing',
            'image_front' => 'power-of-god-singing.png',
            'image_back' => null,
            'image_inner' => null,
            'edition' => '1st',
            'published_at' => '2024-01-10',
            'published' => 1,
            'active' => 1,
            'priority' => 15,
            'page_count' => 46,
            'language' => 'English',
            'price_usd' => '14.99',
            'created_at' => '2026-08-11 14:39:21',
            'updated_at' => '2026-08-11 20:58:58',
            'deleted_at' => null,
        ],
        [
            'title' => 'Cleansing the Soul, the House, and the Land for the Final March',
            'subtitle' => null,
            'slug' => 'cleansing-the-soul-the-house-and-the-land-for-the-final-march',
            'author_id' => 1,
            'body' => '<p>A practical and prophetic manual for the people of Yehovah preparing for the final exodus. This work provides biblical protocols for cleansing—personal (soul), domestic (house), and territorial (land)—based on the Torah patterns of purification, the Levitical priesthood, and the prophetic warnings of the end times.</p><p>Drawing from the Cochin Hebrew manuscripts and the Hebrew roots of the Renewed Covenant, Janice F. Baca presents a step-by-step protocol for spiritual readiness that aligns with the ancient paths of Yehovah\'s people.</p>',
            'isbn_13' => '9781234567893',
            'isbn_10' => '1234567893',
            'amazon_link' => 'https://amazon.com/dp/1234567893',
            'lulu_link' => 'https://lulu.com/shop/janice-baca/cleansing-the-soul',
            'image_front' => 'the-exodus-readiness-manual.jpg',
            'image_back' => null,
            'image_inner' => null,
            'edition' => '1st',
            'published_at' => '2025-04-01',
            'published' => 1,
            'active' => 0,
            'priority' => 20,
            'page_count' => 198,
            'language' => 'English',
            'price_usd' => '16.99',
            'created_at' => '2026-08-11 14:39:21',
            'updated_at' => '2026-08-11 20:59:38',
            'deleted_at' => null,
        ]
        ];

        foreach ($rows as $row) {
            Book::updateOrCreate(
                ['slug' => $row['slug']],
                $row
            );
        }
    }
}
