<?php

namespace Database\Seeders;

use App\Models\Image;
use Illuminate\Database\Seeder;

class ImageSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
        [
            'slug' => 'menorah-women-tabernacle',
            'filename' => 'menorah-women-tabernacle.png',
            'path' => 'images/uploads/menorah-women-tabernacle.png',
            'alt_text' => 'Menorah Women Tabernacle',
            'caption' => null,
            'mime_type' => 'image/png',
            'width' => 1024,
            'height' => 559,
            'file_size' => 941048,
            'category' => 'blog-image, Israel, tabernacle, menorah',
            'created_at' => '2026-08-12 17:22:33',
            'updated_at' => '2026-08-12 17:22:33',
            'deleted_at' => null,
        ],
        [
            'slug' => 'priest-tabernacle-israel',
            'filename' => 'priest-tabernacle-israel.png',
            'path' => 'images/uploads/priest-tabernacle-israel.png',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/png',
            'width' => 1024,
            'height' => 559,
            'file_size' => 945877,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:06:47',
            'updated_at' => '2026-08-12 18:06:47',
            'deleted_at' => null,
        ],
        [
            'slug' => 'woman-sermon-israel-teaching-palm',
            'filename' => 'woman-sermon-israel-teaching-palm.png',
            'path' => 'images/uploads/woman-sermon-israel-teaching-palm.png',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/png',
            'width' => 1024,
            'height' => 559,
            'file_size' => 1228734,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:08:57',
            'updated_at' => '2026-08-12 18:08:57',
            'deleted_at' => null,
        ],
        [
            'slug' => 'women-donkey-fellowship-bread-israel',
            'filename' => 'women-donkey-fellowship-bread-israel.png',
            'path' => 'images/uploads/women-donkey-fellowship-bread-israel.png',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/png',
            'width' => 1024,
            'height' => 559,
            'file_size' => 1198469,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:09:57',
            'updated_at' => '2026-08-12 18:09:57',
            'deleted_at' => null,
        ],
        [
            'slug' => 'yeshua-jesus-scroll',
            'filename' => 'yeshua-jesus-scroll.jpeg',
            'path' => 'images/uploads/yeshua-jesus-scroll.jpeg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 300,
            'height' => 300,
            'file_size' => 15922,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:20:27',
            'updated_at' => '2026-08-12 18:20:27',
            'deleted_at' => null,
        ],
        [
            'slug' => 'scroll',
            'filename' => 'scroll.jpeg',
            'path' => 'images/uploads/scroll.jpeg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 300,
            'height' => 300,
            'file_size' => 16467,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:26:22',
            'updated_at' => '2026-08-12 18:26:22',
            'deleted_at' => null,
        ],
        [
            'slug' => 'hebrew-text-magnifier',
            'filename' => 'hebrew_text-magnifier.jpg',
            'path' => 'images/uploads/hebrew-text-magnifier.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 300,
            'height' => 200,
            'file_size' => 15720,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:27:06',
            'updated_at' => '2026-08-12 18:27:06',
            'deleted_at' => null,
        ],
        [
            'slug' => 'manuscript',
            'filename' => 'manuscript.jpg',
            'path' => 'images/uploads/manuscript.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 300,
            'height' => 200,
            'file_size' => 36821,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:27:58',
            'updated_at' => '2026-08-12 18:27:58',
            'deleted_at' => null,
        ],
        [
            'slug' => 'NOSEARCH-israeli-children',
            'filename' => 'NOSEARCH-israeli-children.jpg',
            'path' => 'images/uploads/NOSEARCH-israeli-children.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 300,
            'height' => 200,
            'file_size' => 15301,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:30:06',
            'updated_at' => '2026-08-13 17:44:31',
            'deleted_at' => null,
        ],
        [
            'slug' => 'child-menorah-candle-tabernacle',
            'filename' => 'child-menorah-candle-tabernacle.jpg',
            'path' => 'images/uploads/child-menorah-candle-tabernacle.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 1024,
            'height' => 1024,
            'file_size' => 99802,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:31:02',
            'updated_at' => '2026-08-12 18:31:02',
            'deleted_at' => null,
        ],
        [
            'slug' => 'children-church',
            'filename' => 'children-church.jpg',
            'path' => 'images/uploads/children-church.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 1024,
            'height' => 683,
            'file_size' => 120223,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:32:09',
            'updated_at' => '2026-08-12 18:32:09',
            'deleted_at' => null,
        ],
        [
            'slug' => 'painting-yeshua-children',
            'filename' => 'painting-yeshua-children.jpg',
            'path' => 'images/uploads/painting-yeshua-children.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 1024,
            'height' => 683,
            'file_size' => 130615,
            'category' => 'blog-inline',
            'created_at' => '2026-08-12 18:33:03',
            'updated_at' => '2026-08-12 18:33:03',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-01',
            'filename' => 'aarons-alter-mount-sinai_01.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-01.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 70295,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:43:16',
            'updated_at' => '2026-08-13 00:43:16',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-02',
            'filename' => 'aarons-alter-mount-sinai_02.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-02.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 81206,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:46:28',
            'updated_at' => '2026-08-13 00:46:28',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-03',
            'filename' => 'aarons-alter-mount-sinai_03.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-03.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 87013,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:46:48',
            'updated_at' => '2026-08-13 00:46:48',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-04',
            'filename' => 'aarons-alter-mount-sinai_04.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-04.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 72754,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:47:11',
            'updated_at' => '2026-08-13 00:47:11',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-05',
            'filename' => 'aarons-alter-mount-sinai_05.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-05.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 97836,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:47:32',
            'updated_at' => '2026-08-13 00:47:32',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-06',
            'filename' => 'aarons-alter-mount-sinai_06.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-06.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 100710,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:47:49',
            'updated_at' => '2026-08-13 00:47:49',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-07',
            'filename' => 'aarons-alter-mount-sinai_07.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-07.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 92607,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:48:34',
            'updated_at' => '2026-08-13 00:48:34',
            'deleted_at' => null,
        ],
        [
            'slug' => 'aarons-alter-mount-sinai-08',
            'filename' => 'aarons-alter-mount-sinai_08.jpg',
            'path' => 'images/uploads/aarons-alter-mount-sinai-08.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 256,
            'file_size' => 69258,
            'category' => 'blog-inline',
            'created_at' => '2026-08-13 00:48:49',
            'updated_at' => '2026-08-13 00:48:49',
            'deleted_at' => null,
        ],
        [
            'slug' => 'well-of-moses-1',
            'filename' => 'well-of-moses-1.png',
            'path' => 'images/uploads/well-of-moses-1.png',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/png',
            'width' => 512,
            'height' => 317,
            'file_size' => 278684,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:40:30',
            'updated_at' => '2026-08-15 13:40:30',
            'deleted_at' => null,
        ],
        [
            'slug' => 'well-of-moses-2',
            'filename' => 'well-of-moses-2.png',
            'path' => 'images/uploads/well-of-moses-2.png',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/png',
            'width' => 512,
            'height' => 287,
            'file_size' => 240649,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:40:48',
            'updated_at' => '2026-08-15 13:40:48',
            'deleted_at' => null,
        ],
        [
            'slug' => 'well-of-moses-3',
            'filename' => 'well-of-moses-3.jpg',
            'path' => 'images/uploads/well-of-moses-3.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 52566,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:41:04',
            'updated_at' => '2026-08-15 13:41:04',
            'deleted_at' => null,
        ],
        [
            'slug' => 'jethro-1',
            'filename' => 'jethro-1.jpg',
            'path' => 'images/uploads/jethro-1.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 317,
            'file_size' => 35097,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:46:10',
            'updated_at' => '2026-08-15 13:46:10',
            'deleted_at' => null,
        ],
        [
            'slug' => 'jethro-2',
            'filename' => 'jethro-2.jpg',
            'path' => 'images/uploads/jethro-2.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 882,
            'height' => 517,
            'file_size' => 92977,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:46:25',
            'updated_at' => '2026-08-15 13:46:25',
            'deleted_at' => null,
        ],
        [
            'slug' => 'jethro-3',
            'filename' => 'jethro-3.jpg',
            'path' => 'images/uploads/jethro-3.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 215,
            'file_size' => 27833,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:46:46',
            'updated_at' => '2026-08-15 13:46:46',
            'deleted_at' => null,
        ],
        [
            'slug' => 'jethro-4',
            'filename' => 'jethro-4.jpg',
            'path' => 'images/uploads/jethro-4.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 251,
            'file_size' => 31560,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:47:13',
            'updated_at' => '2026-08-15 13:47:13',
            'deleted_at' => null,
        ],
        [
            'slug' => 'jethro-5',
            'filename' => 'jethro-5.jpg',
            'path' => 'images/uploads/jethro-5.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 230,
            'file_size' => 32280,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:47:32',
            'updated_at' => '2026-08-15 13:47:32',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-1',
            'filename' => 'nuweiba-1.jpg',
            'path' => 'images/uploads/nuweiba-1.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 273,
            'file_size' => 75552,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:51:48',
            'updated_at' => '2026-08-15 13:51:48',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-2',
            'filename' => 'nuweiba-2.jpg',
            'path' => 'images/uploads/nuweiba-2.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 384,
            'height' => 512,
            'file_size' => 51880,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:51:59',
            'updated_at' => '2026-08-15 13:51:59',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-3',
            'filename' => 'nuweiba-3.jpg',
            'path' => 'images/uploads/nuweiba-3.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 512,
            'height' => 384,
            'file_size' => 45285,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:52:09',
            'updated_at' => '2026-08-15 13:52:09',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-4',
            'filename' => 'nuweiba-4.jpg',
            'path' => 'images/uploads/nuweiba-4.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 2560,
            'height' => 1920,
            'file_size' => 582300,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:52:27',
            'updated_at' => '2026-08-15 13:52:27',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-5',
            'filename' => 'nuweiba-5.jpg',
            'path' => 'images/uploads/nuweiba-5.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 2560,
            'height' => 1920,
            'file_size' => 1161996,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:52:38',
            'updated_at' => '2026-08-15 13:52:38',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-6',
            'filename' => 'nuweiba-6.jpg',
            'path' => 'images/uploads/nuweiba-6.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 2560,
            'height' => 1920,
            'file_size' => 1848969,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:52:51',
            'updated_at' => '2026-08-15 13:52:51',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-7',
            'filename' => 'nuweiba-7.jpg',
            'path' => 'images/uploads/nuweiba-7.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 1920,
            'height' => 2560,
            'file_size' => 1921460,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:53:06',
            'updated_at' => '2026-08-15 13:53:06',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-8',
            'filename' => 'nuweiba-8.jpg',
            'path' => 'images/uploads/nuweiba-8.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 1920,
            'height' => 2560,
            'file_size' => 1606056,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:53:16',
            'updated_at' => '2026-08-15 13:53:16',
            'deleted_at' => null,
        ],
        [
            'slug' => 'nuweiba-9',
            'filename' => 'nuweiba-9.jpg',
            'path' => 'images/uploads/nuweiba-9.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 1920,
            'height' => 2560,
            'file_size' => 570270,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 13:53:26',
            'updated_at' => '2026-08-15 13:53:26',
            'deleted_at' => null,
        ],
        [
            'slug' => 'img-4385',
            'filename' => 'IMG_4385.JPG',
            'path' => 'images/uploads/img-4385.jpg',
            'alt_text' => null,
            'caption' => null,
            'mime_type' => 'image/jpeg',
            'width' => 1200,
            'height' => 1200,
            'file_size' => 235291,
            'category' => 'blog-inline',
            'created_at' => '2026-08-15 15:20:15',
            'updated_at' => '2026-08-15 15:20:15',
            'deleted_at' => null,
        ]
        ];

        foreach ($rows as $row) {
            Image::updateOrCreate(
                ['slug' => $row['slug']],
                $row
            );
        }
    }
}
