<?php

namespace Database\Seeders;

use App\Models\Video;
use Illuminate\Database\Seeder;

class VideoSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
        [
            'slug' => 'cambridge-cochin-hebrew-matthew-5',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Matthew Chapter 5: Amazing Discoveries Series (Part 2)',
            'description' => 'In this video series there is amazing discoveries being presented from the Cochin Hebrew Matthew. We are examining unique places where the text differs from the traditional Greek/English versions. Many of these places will either add clarity to the confusion of the text or possible solve textual problems that have plagued scholars/researchers for well over a thousand years. We hope you enjoy the show. Please also check out ProjectTruthMinistries.org for downloading our translations and learning about our ministry.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=gVEV0U6zzFk',
            'source_platform' => 'youtube',
            'source_id' => 'gVEV0U6zzFk',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-13 15:35:19',
            'updated_at' => '2026-08-14 23:49:57',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-hebrew-matthew',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Matthew 16:21',
            'description' => 'Examining one different word in the Cochin Hebrew Matthew compared to the Greek/English versions. One word changes the whole meaning of what was about to unfold for the Messiah.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=G_BSPspH-zg',
            'source_platform' => 'youtube',
            'source_id' => 'G_BSPspH-zg',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-15 01:32:17',
            'updated_at' => '2026-08-15 01:32:17',
            'deleted_at' => null,
        ],
        [
            'slug' => 'alpha-and-omega-problem-hebrew-manuscripts-revelation-cochin',
            'filename' => null,
            'path' => null,
            'title' => 'The Alpha and Omega Problem',
            'description' => '#bible #hebrew #manuscripts #ProjectTruthMinistries #HebrewRevelation #cochin
In this video we are recapping all the places where the Alpha and Omega is mentioned in the Greek book of Revelation.
Stay tuned for the next video!
If you would like to download your own version of the Cochin Hebrew Revelation go to our website at ProjectTruthMinistries.org or you can go to www.academia.edu Here is the link below!',
            'category' => 'Cochin',
            'source_url' => 'https://rumble.com/v70ilku-the-alpha-and-omega-problem.html',
            'source_platform' => 'rumble',
            'source_id' => 'v70ilku-the-alpha-and-omega-problem',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-13 15:38:13',
            'updated_at' => '2026-08-13 15:38:54',
            'deleted_at' => null,
        ],
        [
            'slug' => 'lighting-brimstone-from-gomorrah',
            'filename' => null,
            'path' => null,
            'title' => 'Lighting Brimstone From Gomorrah',
            'description' => 'Lighting Brimstone From Gomorrah',
            'category' => 'Shorts',
            'source_url' => 'https://rumble.com/shorts/vbqkdp',
            'source_platform' => 'rumble',
            'source_id' => 'shorts',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-13 15:40:18',
            'updated_at' => '2026-08-13 15:40:18',
            'deleted_at' => null,
        ],
        [
            'slug' => 'music-in-jerusalem-shofar-drum-trumpet',
            'filename' => null,
            'path' => null,
            'title' => 'Music in Jerusalem',
            'description' => 'Trumpets and shofars and drums!',
            'category' => 'Shorts',
            'source_url' => 'https://rumble.com/vbqal7-music-in-jerusalem.html',
            'source_platform' => 'rumble',
            'source_id' => 'vbqal7-music-in-jerusalem',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-13 15:41:43',
            'updated_at' => '2026-08-13 15:42:09',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-Hebrew-Matthew-4',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Matthew Chapter 4: Amazing Discoveries Series',
            'description' => 'In this video series there is amazing discoveries being presented from the Cochin Hebrew Matthew. We are examining unique places where the text differs from the traditional Greek/English versions. Many of these places will either add clarity to the confusion of the text or possible solve textual problems that have plagued scholars/researchers for well over a thousand years. We hope you enjoy the show. Please also check out ProjectTruthMinistries.org for downloading our translations and learning about our ministry.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=GlgfAxxqu2w',
            'source_platform' => 'youtube',
            'source_id' => 'GlgfAxxqu2w',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:45:12',
            'updated_at' => '2026-08-14 23:45:12',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-Hebrew-Matthew-3',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Matthew Chapter 3: Amazing Discoveries Series',
            'description' => 'In this video series there is amazing discoveries being presented from the Cochin Hebrew Matthew. We are examining unique places where the text differs from the traditional Greek/English versions. Many of these places will either add clarity to the confusion of the text or possible solve textual problems that have plagued scholars/researchers for well over a thousand years. We hope you enjoy the show. Please also check out ProjectTruthMinistries.org for downloading our translations and learning about our ministry.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=kTid0p1x-FM',
            'source_platform' => 'youtube',
            'source_id' => 'kTid0p1x-FM',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:46:18',
            'updated_at' => '2026-08-14 23:46:18',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-Hebrew-Matthew-2',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Matthew Chapter 2: Amazing Discoveries Series',
            'description' => 'In this video series there is amazing discoveries being presented from the Cochin Hebrew Matthew. We are examining unique places where the text differs from the traditional Greek/English versions. Many of these places will either add clarity to the confusion of the text or possible solve textual problems that have plagued scholars/researchers for well over a thousand years. We hope you enjoy the show. Please also check out ProjectTruthMinistries.org for downloading our translations and learning about our ministry.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=eLOgn2WZi3M',
            'source_platform' => 'youtube',
            'source_id' => 'eLOgn2WZi3M',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:47:15',
            'updated_at' => '2026-08-14 23:47:15',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-Hebrew-Matthew-1',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Matthew Chapter 1: Amazing Discoveries Series',
            'description' => 'This is the amazing discoveries series on the Cochin Hebrew Matthew. We are examining unique places where the text differs from the traditional Greek/English versions. Many of these places will either add clarity to the confusion of the text or possible solve textual problems that have plagued scholars/researchers for well over a thousand years. We hope you enjoy the show. Please also check out ProjectTruthMinistries.org for downloading our translations and learning about our ministry.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=Pxcc0Xr7GKI',
            'source_platform' => 'youtube',
            'source_id' => 'Pxcc0Xr7GKI',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:48:07',
            'updated_at' => '2026-08-14 23:48:07',
            'deleted_at' => null,
        ],
        [
            'slug' => 'cambridge-cochin-hebrew-revelation-destoryer',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Revelation The Destroyer',
            'description' => 'In this video we are looking at a place in the Cochin Hebrew Revelation where it does not say old serpent rather it uses the term found in Exodus called the destroyer. This is a significant find because it links up the Old Testament with the Revelation.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=vGI5Tjn9riY',
            'source_platform' => 'youtube',
            'source_id' => 'vGI5Tjn9riY',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:51:40',
            'updated_at' => '2026-08-14 23:51:40',
            'deleted_at' => null,
        ],
        [
            'slug' => 'cambridge-cochin-hebrew-aramaic',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Manuscripts Do Not Come from the Aramaic',
            'description' => null,
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=xlkpil_EMOc',
            'source_platform' => 'youtube',
            'source_id' => 'xlkpil_EMOc',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:54:43',
            'updated_at' => '2026-08-14 23:54:43',
            'deleted_at' => null,
        ],
        [
            'slug' => 'saudi-arabian-codices',
            'filename' => null,
            'path' => null,
            'title' => 'Saudi Arabian Codices Exposed!',
            'description' => 'In this video you will see Janice Baca and Bryan Williams tell their story about the discovery of the Saudi Arabian Codices. They also walk you through images on the gold and lead tablets. They also explain what the origins story is and also discuss the credibility. They also show a connection to the Jordan Lead Codices. We hope you enjoy.',
            'category' => 'Teaching',
            'source_url' => 'https://www.youtube.com/watch?v=tx2PVxkxiqQ',
            'source_platform' => 'youtube',
            'source_id' => 'tx2PVxkxiqQ',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:55:48',
            'updated_at' => '2026-08-14 23:55:48',
            'deleted_at' => null,
        ],
        [
            'slug' => 'rock-horeb-saudi-arabia-moses',
            'filename' => null,
            'path' => null,
            'title' => 'That Rock at Horeb',
            'description' => 'This video is about the split rock of Moses found in the Bible. The remains of this split rock still there today in Saudi Arabia.',
            'category' => 'Teaching',
            'source_url' => 'https://www.youtube.com/watch?v=_6l86ho1aA4',
            'source_platform' => 'youtube',
            'source_id' => '_6l86ho1aA4',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:57:53',
            'updated_at' => '2026-08-14 23:57:53',
            'deleted_at' => null,
        ],
        [
            'slug' => 'cambridge-cochin-revelation-hebrew',
            'filename' => null,
            'path' => null,
            'title' => 'Reveal-ation!!! The story revealed!!',
            'description' => 'This is a tell all of most of the crazy things we had to face while trying to put out the Cochin Hebrew Revelations “The Scroll of Mysteries.”whether it was publishing or creating the walkthrough study we faced all kinds of obstacles.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=xaxm7PEy-WE',
            'source_platform' => 'youtube',
            'source_id' => 'xaxm7PEy-WE',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-14 23:59:16',
            'updated_at' => '2026-08-14 23:59:16',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-Hebrew-Matthew-24',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Matthew 24:24',
            'description' => 'Examining one different word in the Cochin Hebrew Matthew compared to the Greek/English versions. One word changes the whole meaning of what was about to unfold for the Messiah.',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=OSEOieBpt_Y',
            'source_platform' => 'youtube',
            'source_id' => 'OSEOieBpt_Y',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-15 00:01:57',
            'updated_at' => '2026-08-15 00:01:57',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-Hebrew-Matthew-22',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Revelation: The Scroll of Mysteries Chapter 22',
            'description' => 'This is a very historic thing examining a newly translated Hebrew Revelation from Cochin India. PTM has invited you to watch us examine it on camera and talk about the findings of this manuscript. There have been a lot things found in the manuscript pointing to this being a copy of a copy of a copy that comes from a first century Hebrew source. This will be amazing! Stay tuned for the next video! 
If you would like to download your own version of the Cochin Hebrew Revelation go to our website at ProjectTruthMinistries.org or you can go to www.academia.edu',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=ouhNzhLTGt8',
            'source_platform' => 'youtube',
            'source_id' => 'ouhNzhLTGt8',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-15 00:03:46',
            'updated_at' => '2026-08-15 00:03:46',
            'deleted_at' => null,
        ],
        [
            'slug' => 'Cambridge-Cochin-Hebrew-Revelation',
            'filename' => null,
            'path' => null,
            'title' => 'Cochin Hebrew Revelation: The Scroll of Mysteries Chapter 19 (Part 2)',
            'description' => 'This is a very historic thing examining a newly translated Hebrew Revelation from Cochin India. PTM has invited you to watch us examine it on camera and talk about the findings of this manuscript. There have been a lot things found in the manuscript pointing to this being a copy of a copy of a copy that comes from a first century Hebrew source. This will be amazing! Stay tuned for the next video!',
            'category' => 'Cochin',
            'source_url' => 'https://www.youtube.com/watch?v=hFxfSwpK5hQ',
            'source_platform' => 'youtube',
            'source_id' => 'hFxfSwpK5hQ',
            'file_size' => null,
            'mime_type' => null,
            'duration' => null,
            'thumbnail_path' => null,
            'published' => 1,
            'created_at' => '2026-08-15 01:43:31',
            'updated_at' => '2026-08-15 01:43:31',
            'deleted_at' => null,
        ]
        ];

        foreach ($rows as $row) {
            Video::updateOrCreate(
                ['slug' => $row['slug']],
                $row
            );
        }
    }
}
